export default {
    content: [
      "./index.html",
      "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          brand: {
            midnight: '#2A2E33',
            primary: '#0641FC',
            cobalt: '#016FD0',
            indigo: '#1633CA',
            sky: '#4285F4',
            ice: '#9DB5FF',
            mint: '#2FCD66',
            emerald: '#34A853',
            frost: '#D1DCFF',
          },
          neutral: {
            white: '#FFFFFF',
            porcelain: '#F9F9F9',
            cotton: '#F5F5F5',
            cloud: '#F0F0F0',
            snow: '#EEEEEE',
            eggshell: '#E6E3DC',
            ash: '#D6D2C7',
            stone: '#C7C2B4',
            fog: '#D9D9D9',
            slate: '#86898B',
            pine: '#003933',
            charcoal: '#212B34',
            graphite: '#11151B',
            midnight: '#00000A',
            black: '#000000',
          },
          accent: {
            purple: '#852DF6',
            lilac: '#B882FE',
            amber: '#FABB05',
            sunshine: '#FFED00',
            yellow: '#FFFF00',
            saffron: '#E5E500',
            olive: '#A2A203',
            moss: '#484807',
            success: '#2FCD66',
            successDeep: '#34A853',
            orange: '#ED6B06',
            tangerine: '#F89E26',
            apricot: '#FF9D3A',
            peach: '#FFE8D1',
            scarlet: '#E94235',
            crimson: '#EC0021',
            burgundy: '#B3131B',
            carrot: '#FF5D11',
          },
        },
      },
    },
    plugins: [],
  }